### ISSUE TITLE
Can you please add "无底牌" option? Also can you please add option to customize the scores for winning the round and leveling up?

### ISSUE THREAD

**Issue by chnlyi** [rbtying/shengji#188] opened 2020-07-18 15:44 UTC
I have introduced your game to several friends of mine.
We find it an excellent game for remote playing.
We like to play with many decks. In that case, the current scoring for winning the round and leveling up is in favor of the landlord. 
So can you please add these 2 features so that we can play it more balanced? 
Thanks!

**Comment by rbtying** [comment] 2020-07-18 18:39
Hey! Glad to hear you are enjoying the game.

It should be easy enough to add option for no 底牌.

What would you like to see for the round breakdowns?

**Comment by rbtying** [comment] 2020-07-18 18:39
similar to #141 ?

**Comment by chnlyi** [comment] 2020-07-18 18:56
Right!
The level breakdowns maybe 80 points or whatever so that it is easy to go
up levels.
Thanks a lot!

**Comment by rbtying** [comment] 2020-08-08 05:12
closing this out because it is a duplicate of #141

**Closed by rbtying** 2020-08-08 05:12 UTC
