### ISSUE TITLE
[BUG] Kitty is always visible at the bottom of the screen

### ISSUE THREAD

**Issue by Dorenavant** [rbtying/shengji#336] opened 2021-06-30 02:27 UTC

**Comment by rbtying** [comment] 2021-06-30 02:46
@Dorenavant Do you mind sending a screenshot of what the issue is, along with what your settings are?

**Comment by rbtying** [comment] 2021-06-30 04:06
Fixed by https://github.com/rbtying/shengji/commit/90bbde61160a1db85ed9279b43443bf03b69002f

**Closed** 2021-06-30 04:07 UTC

**Comment by Dorenavant** [comment] 2021-06-30 22:26
Thanks for the quick fix :) cheers
