### ISSUE TITLE
Landlord become his own friend

### ISSUE THREAD

**Issue by blu-world** [rbtying/shengji#421] opened 2023-02-15 06:08 UTC
It seems the behavior changed with the finding friends (played on Feb. 14, 2023)
- It seems that when call friend , say the 1st of Club A and landlord played a Club A 1st and that consider that the landlord is his own friend. It's not used to be like that. Is there a option to setting that the landlord playing the "friend card" does not count or landlord can't be his own friend?

**Comment by rbtying** [comment] 2023-02-15 06:43
Yes, there is a game setting so that the landlord cannot be their own friend

![image](https://user-images.githubusercontent.com/918977/218952378-99e63200-7e71-4b05-8f11-54c761ed0750.png)

Under "difficulty settings" you can change this.

**Comment by blu-world** [comment] 2023-02-15 16:15
So, that makes the any player can be friend multiple times, even the landlord himself?! I thought that would only make the other player to be "friend" instead of himself though.
So you can not having the option that will allow the other player  be friend multiple time but not the landlord?

**Comment by rbtying** [comment] 2023-02-15 17:09
Yes, right now the option is for anyone to join multiple times. In #328 there was a request to allow landlord to request “other”, but i haven’t implemented that yet

**Comment by rbtying** [comment] 2023-02-15 17:09
(though, the behavior hasn’t changed; it’s been this way for at least a year)

**Comment by rbtying** [comment] 2023-02-25 05:02
closing as duplicate of #328

**Closed by rbtying** 2023-02-25 05:02 UTC
